version: 2

models:
  - name: my_model
    description: test model
    columns:
      - name: _airbyte_extracted_at
      - name: _airbyte_meta
      - name: _airbyte_raw_id
      - name: addr_state
        description: The state in which the borrower resides
      - name: annual_inc
        description: The borrower's annual income
      - name: collections_12_mths_ex_med
        description: Number of collections in the last 12 months excluding medical collections
      - name: collection_recovery_fee
        description: Post charge off collection fee
      - name: delinq_2yrs
        description: The number of 30+ days past-due incidences of delinquency in the borrower's credit file for the past 2 years
      - name: desc
        description: Loan description provided by the borrower
      - name: dti
        description: The borrower's debt-to-income ratio
      - name: earliest_cr_line
        description: The month the borrower's earliest reported credit line was opened
      - name: emp_length
        description: Employment length in years
      - name: emp_title
        description: The job title supplied by the borrower when applying for the loan
      - name: funded_amnt
        description: The total amount committed to that loan at that point in time
      - name: funded_amnt_inv
        description: The total amount committed by investors for that loan at that point in time
      - name: grade
        description: LC assigned loan grade
      - name: home_ownership
        description: The home ownership status provided by the borrower during registration
      - name: initial_list_status
        description: The initial listing status of the loan
      - name: inq_last_6mths
        description: The number of inquiries in past 6 months (excluding auto and mortgage inquiries)
      - name: installment
        description: The monthly payment owed by the borrower if the loan originates
      - name: int_rate
        description: Interest rate on the loan
      - name: issue_d
        description: The month which the loan was funded
      - name: last_credit_pull_d
        description: The most recent month LC pulled credit for this loan
      - name: last_pymnt_amnt
        description: Last total payment amount received
      - name: last_pymnt_d
        description: Last month payment was received
      - name: loan_amnt
        description: The listed amount of the loan applied for by the borrower
      - name: loan_id
        description: A unique identifier for the loan
      - name: loan_status
        description: Current status of the loan
      - name: member_id
        description: A unique identifier for the borrower
      - name: mths_since_last_delinq
        description: The number of months since the borrower's last delinquency
      - name: mths_since_last_major_derog
        description: Months since most recent 90-day or worse rating
      - name: mths_since_last_record
        description: The number of months since the last public record
      - name: next_pymnt_d
        description: Next scheduled payment date
      - name: open_acc
        description: The number of open credit lines in the borrower's credit file
      - name: out_prncp
        description: Remaining outstanding principal for total amount funded
      - name: out_prncp_inv
        description: Remaining outstanding principal for portion of total amount funded by investors
      - name: policy_code
        description: Publicly available
      - name: pub_rec
        description: Number of derogatory public records
      - name: purpose
        description: A category provided by the borrower for the loan request
      - name: pymnt_plan
        description: Indicates if a payment plan has been put in place for the loan
      - name: recoveries
        description: Post charge off gross recovery
      - name: revol_bal
        description: Total credit revolving balance
      - name: revol_util
        description: Revolving line utilization rate, or the amount of credit the borrower is using relative to all available revolving credit
      - name: sub_grade
        description: LC assigned loan subgrade
      - name: term
        description: The number of payments on the loan. Values are in months and can be either 36 or 60
      - name: title
        description: The loan title provided by the borrower
      - name: total_acc
        description: The total number of credit lines currently in the borrower's credit file
      - name: total_pymnt
        description: Payments received to date for total amount funded
      - name: total_pymnt_inv
        description: Payments received to date for portion of total amount funded by investors
      - name: total_rec_int
        description: Interest received to date
      - name: total_rec_late_fee
        description: Late fees received to date
      - name: total_rec_prncp
        description: Principal received to date
      - name: url
        description: URL for the LC page with listing data
      - name: verification_status
        description: Indicates if income was verified by LC, not verified, or if the income source was verified
      - name: zip_code
        description: The first 3 numbers of the zip code provided by the borrower in the loan application
