# This is a minimum working example of how
# copier can be used to better manage dbt-coves
# files. It can be extended well beyond this.

adapter:
  type: str
  choices:
    - snowflake
    - bigquery
    - redshift
    - postgres
    - spark
    - sqlite
    - duckdb
  help: What dbt adapter are you using?

comma_style:
  type: str
  choices:
    - leading
    - trailing
  help: Where should commas be placed?
  default: trailing
