name: Test pip install

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: PIP Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: "poetry"

      - name: run Pre-Commit
        uses: pre-commit/action@v3.0.0

      - name: Build dbt-coves using Poetry
        run: |
          poetry build

      - name: Discover .whl file
        id: discover_whl
        run: |
          ls dist/*.whl | grep -E "dbt_coves-[0-9]+\.[0-9]+\.[0-9]+-py3-none-any\.whl" | head -n 1 > whl_file.txt

      - name: Extract .whl file name
        id: extract_whl_name
        run: |
          WHL_FILE=$(cat whl_file.txt)
          echo "::set-output name=whl_file::$WHL_FILE"

      - name: Use .whl to pip-install
        run: |
          WHL_FILE_PATH=${{ steps.extract_whl_name.outputs.whl_file }}
          pip install $WHL_FILE_PATH
