name: Test pip install

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: PIP Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.9.x"
          python-version: "3.9"
          enable-cache: true

      - name: run Pre-Commit
        uses: pre-commit/action@v3.0.0

      - name: Build dbt-coves using uv
        run: |
          uv build

      - name: Discover .whl file
        id: discover_whl
        run: |
          ls dist/*.whl | grep -E "dbt_coves-[0-9]+\.[0-9]+\.[0-9]+-py3-none-any\.whl" | head -n 1 > whl_file.txt

      - name: Extract .whl file name
        id: extract_whl_name
        run: |
          WHL_FILE=$(cat whl_file.txt)
          echo "::set-output name=whl_file::$WHL_FILE"

      - name: pip install dbt-coves
        run: |
          WHL_FILE_PATH=${{ steps.extract_whl_name.outputs.whl_file }}
          pip install $WHL_FILE_PATH
